version: '3.1'

services:
  mysql:
    image: mysql
    command: --authentication-policy=mysql_native_password
    restart: always
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "33061:3306"



